-- ENUM drift 수정: TS에 정의된 VICE_PRESIDENT, ADVISOR, MATCH_DIRECTOR를 DB ENUM에 추가
-- ADD VALUE는 트랜잭션 내 롤백 불가이므로 단독 실행
ALTER TYPE club_member_role ADD VALUE IF NOT EXISTS 'VICE_PRESIDENT';
ALTER TYPE club_member_role ADD VALUE IF NOT EXISTS 'ADVISOR';
ALTER TYPE club_member_role ADD VALUE IF NOT EXISTS 'MATCH_DIRECTOR';
